const express= require('express')
const router= express.Router()
const user=require('../controllers/userController')
const product=require('../controllers/productController')
const {authentication,authorization}=require('../authentication/auth')
router.post('/register', user.createUser)
router.post('/login',user.login)  
router.get('/user/:userId/profile',authentication,user.getUser)
router.put('/user/:userId/profile',authentication,authorization,user.updateUser)
router.post('/products',product.createProduct)
router.get('/products',product.getProducts)
router.get('/products/:productId',product.getProduct)
router.put('/products/:productId',product.updateProduct)
router.delete('/products/:productId',product.deleteProduct)
module.exports=router